name: Desktop CI

on:
  push:
    branches: [ compose-mm ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Build with Gradle
      run: ./gradlew assemble

